Parcial/Models/ErrorViewModel.cs
namespace Parcial.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Parcial/Models/Formulario.cs
namespace Parcial.Models
{
    public class Formulario
    {
        public string Condicion_Iva { get; set; }
        

        public double Cuit { get; set; }

        public string Razon_Social { get; set; }
        public string Domicilio { get; set; }
        public string Email { get; set; }
        public string Condicion_Venta { get; set; }
    }
}

Parcial/Controllers/FormularioController.cs
using Parcial.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Reflection;

namespace Parcial.Controllers
{
    public class FormularioController : Controller
    {

        public static List<Formulario> formularioList = new List<Formulario>();
        public IActionResult Index()
        {

            return View(formularioList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create(Formulario pag)
        {
            try
            {
                formularioList.Add(pag);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        /* [HttpPost]
         public IActionResult Create(IDtributaria tarea)
         {
             tarea.Id = tributaria.Count + 1;
             tarea.Id = tributaria.Count + 1;
             tributaria.Add(tarea);
             return RedirectToAction("Index");
         }*/
    }
}

Parcial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Parcial.Models;
using System.Diagnostics;

namespace Parcial.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Parcial/Views/Formulario/Create.cshtml
@model Parcial.Models.Formulario
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Create</h1>

<h4>Formulario de Rgistro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">

                <label asp-for="Condicion_Iva" class="control-label">Condicion de Iva</label>
                @* seleccion de item, asp-for="condIva" no tengo pruebas y tampoco dudas que es loq eu tomara  el valor para madnarlo en el selector*@
                <select asp-for="Condicion_Iva" id="card" class="form-control">
                    <option value="Monotributistas">Monotributistas</option>
                    <option value="Responsable Inscripto">Responsable Inscripto</option>
                    <option value="Exento">Exento</option>
                </select>
                @*<input asp-for="CondIva" class="form-control" />*@
                <span asp-validation-for="Condicion_Iva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuit" class="control-label"></label>
                <input asp-for="Cuit" minlength="10" class="form-control" />
                <span asp-validation-for="Cuit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Razon_Social" class="control-label"></label>
                <input asp-for="Razon_Social" class="form-control" />
                <span asp-validation-for="Razon_Social" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Domicilio" class="control-label"></label>
                <input asp-for="Domicilio" class="form-control" />
                <span asp-validation-for="Domicilio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" type="email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Condicion_Venta" class="control-label">Condicion de venta</label>
                <br />
                <ol>
                    <label asp-for="Condicion_Venta" class="control-label">Contado</label>
                    
                    <input asp-for="Condicion_Venta" type="checkbox" value="Contado">
                    <br />
                    <label asp-for="Condicion_Venta" class="control-label">Cheques</label>
                    <input asp-for="Condicion_Venta" type="checkbox" value="Cheques">
                    <br />
                    <label asp-for="Condicion_Venta" class="control-label">Ticket</label>
                    <input asp-for="Condicion_Venta" type="checkbox" value="Ticket">
                    <br />
                    <label asp-for="Condicion_Venta" class="control-label">Otros</label>

                    <input asp-for="Condicion_Venta" type="checkbox" value="Otros">
                </ol>
                <span asp-validation-for="Condicion_Venta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <br />
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Parcial/Views/Formulario/Index.cshtml
@model IEnumerable<Parcial.Models.Formulario>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Datos de Registro</h1>

<p>
    <a asp-action="Create"><input type="submit" value="Agregar" class="btn btn-primary" /></a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Condicion_Iva)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Razon_Social)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Domicilio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Condicion_Venta)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Condicion_Iva)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cuit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Razon_Social)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Domicilio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Condicion_Venta)
                </td>
                <td>

                    <a asp-action="Edit" asp-route-id="@item.Cuit"> <input type="submit" value="Editar" class="btn btn-primary" /></a> |
                    <a asp-action="Details" asp-route-id="@item.Cuit"><input type="submit" value="Detalle" class="btn btn-primary" /></a> |
                    <a asp-action="Delete" asp-route-id="@item.Cuit"><input type="submit" value="Borrar" class="btn btn-primary" /></a>
                  
                </td>
                
            </tr>
        }
    </tbody>
</table>

Parcial/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "1er Parcial";
}

<div class="text-center">
    <h1 class="display-4">Integrantes del grupo</h1>
    <p>Edison Morillo</p>
    <p>Leandro Colarte</p>
    <p>Jorge Cruz Ricaldy</p>
</div>

Parcial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parcial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Parcial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Index">Formulario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacida</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Parcial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>